### ISSUE TITLE
Update requirements.txt to match Python 3.8+ and Django2.2 tech stack 

### ISSUE THREAD

**Issue by ptomasula** [LimnoTech/WEBTSA#1]

**Comment by ptomasula** [comment]
@aufdenkampe 

I'm working on the various refactoring efforts in the [Python3.6+ branch](https://github.com/LimnoTech/WEBTSA/tree/Python3.6+). I just committed [0fe8ba9](https://github.com/LimnoTech/WEBTSA/commit/0fe8ba9e7816a9edeb7c683d1dcdb6f9efc5f3ac) which updates the requirements.txt file to match the modern dependencies. 

Would you be able to take that file and convert it to an equivalent environment.yml or other Conda environment generation file?

**Comment by aufdenkampe** [comment]
@ptomasula, will do. Are you OK if I actually upgrade to Python 3.8+?

Python 3.6 has lots of issues and I think Python 3.7 is no longer in Long Term Support as of very recently.
Meanwhile, most libraries we use have already been released with "binary wheels" for Python 3.9.

**Comment by ptomasula** [comment]
Sure. My install is actually on Python 3.8 so that's not issue on my end. I'll rename our working branch and will move forward with 3.8+ support.

**Comment by ptomasula** [comment]
@aufdenkampe 

Ok, I've renamed our feature branch and updated the requirements.txt file to require python>=3.8. You should be all set to convert it to a yml file.

**Comment by ptomasula** [comment]
We ultimately made the decision to replaced TSA as noted in ODM2DataSharing Portal #512, thereby eliminating the need to implement this issue.
