### ISSUE TITLE
Eliminate dependency of ODM1/TSA Catalog Table & InfluxDB 

### ISSUE THREAD

**Issue by ptomasula** [LimnoTech/WEBTSA#2]
Currently the WEBTSA API models require and intermediary data table in the product data called TSA Catalog. This table acts as a mapping from the ODM2 schema (used by the rest of the Monitor My Watershed application) and the data models used by TSA. 

Refactor the WEBTSA API models to eliminate the need for the intermediary table and directly access the data from the ODM2 schema.

**Comment by aufdenkampe** [comment]
This is connected to https://github.com/ODM2/ODM2DataSharingPortal/issues/434 (**Replace InfluxDB with the TimescaleDB extension to PostgreSQL**).

**Comment by ptomasula** [comment]
@aufdenkampe 

The TSA application's API really only looks to be using a single [DataSeries ](https://github.com/LimnoTech/WEBTSA/blob/53a6e7c8d9c9516260f2504ce8db310a83124823/src/webtsaservices/models.py#L19-L60) model. This will probably simplify this effort. We just need to create enough models to maintain the functionality currently provided by that class. Even then, we really only need to support read operations, since no actual data manipulation is done within TSA. 

I think next step if for you and I to meet to briefly talk about a crosswalk between the TSA Catalog fields and the current ODM2 schema. I put together a spreadsheet on our network, which I emailed to you, but I also found the [GenerateCatalogFromODM.sql](https://github.com/LimnoTech/WEBTSA/blob/Python3.8+/src/TSACatalogGeneration/GenerateCatalogFromODM.sql) file this morning. This looks to be the query that generates the TSACatalog.DataSeries table, and so probably has most (all?) of the crosswalk information in it.

**Comment by aufdenkampe** [comment]
@ptomasula, thanks for this sleuthing!

The [GenerateCatalogFromODM.sql](https://github.com/LimnoTech/WEBTSA/blob/Python3.8+/src/TSACatalogGeneration/GenerateCatalogFromODM.sql) file is definitely helpful, but it was last edited in January 2015, before we started work on Monitor My Watershed in late 2016. Therefore, it might apply to a different implementation (maybe ODM1) and not be fully relevant.

Some relevant files might actually be here: https://github.com/ODM2/ODM2DataSharingPortal/commits/develop/src/tsa

or here: 
-  https://github.com/ODM2/ODM2DataSharingPortal/blob/master/src/dataloaderinterface/management/commands/rebuild_tsa_catalog.py
- https://github.com/ODM2/ODM2DataSharingPortal/blob/master/src/dataloaderinterface/management/commands/generate_influx_data.py

As documented here: https://github.com/LimnoTech/ODM2DataSharingPortalConfig/wiki/Development-Workflows#update--fix-influxdb-data--connections-for-webtsa--sparklines

**Comment by ptomasula** [comment]
We ultimately made the decision to replaced TSA as noted in [ODM2DataSharing Portal #512](https://github.com/ODM2/ODM2DataSharingPortal/issues/512), thereby eliminating the need to implement this issue.
